dierendeterminatie:
  dierendeterminatie.cloud.naturalis.nl:
    serveraliases: *.cloud.naturalis.nl
    docroot: /var/www/dierendeterminatie
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl

mysql::config::default_engine: myisam

monophylizer:
  monophylizer.cloud.naturalis.nl:
    serveraliases: *.cloud.naturalis.nl
    docroot: /var/www/monophylizer
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl
    options: +FollowSymLinks +ExecCGI

monophylizer::config::repo: https://github.com/ncbnaturalis/monophylizer.git

