virtualhosts:
  apache-default.cloud.naturalis.nl:
    serveraliases: *.cloud.naturalis.nl
    docroot: /var/www
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl

mysql::config::default_engine: myisam

monophylizer:
  monophylizer.cloud.naturalis.nl:
    serveraliases: *.cloud.naturalis.nl
    docroot: /var/www/monophylizer
    port: 80
    ssl: no
    serveradmin: bestaatniet@naturalis.nl

monophylizer::config::repo: https://github.com/ncbnaturalis/monophylizer.git

